#!/usr/bin/with-contenv bash

##
# Replace real app details and license here
##
if [ -n "$NR_LICENSE_KEY" ]; then

  sed -i "s|%%NR_LICENSE_KEY%%|$NR_LICENSE_KEY|g" /etc/php5/conf.d/newrelic.ini

fi

if [ -n "$NR_APP_NAME" ]; then

  sed -i "s|%%NR_APP_NAME%%|$NR_APP_NAME|g" /etc/php5/conf.d/newrelic.ini

fi
